name = "my-worker"
type = "javascript"

[env.production]
name = "my-worker"
type = "javascript"

[[env.production.r2_buckets]]
binding = "MY_R2_BUCKET"  # Название Binding для вашего R2 бакета
bucket_name = "bymovie"   # Имя вашего R2 бакета
